server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=0
            

        - id: course-service
          uri: lb://course-service
          predicates:
            - Path=/api/courses/**
          filters:
            - StripPrefix=0

        - id: exam-service
          uri: lb://exam-service
          predicates:
            - Path=/api/exams/**,/api/results/**
          filters:
            - StripPrefix=0

        - id: discovery-server
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=0

        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/api/subscriptions/**
          filters:
            - StripPrefix=0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

# Enable actuator endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

# Logging configuration
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
    com.elearningsystem.apigateway.filter: DEBUG
    org.springframework.web.server: DEBUG 