server:
  port: 8084

spring:
  application:
    name: exam-service
  
  # H2 Database Configuration
  datasource:
    url: jdbc:h2:mem:examdb
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  # H2 Console (for development/testing)
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,circuitbreakers,retries,bulkheads,timelimiters
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    circuitbreakers:
      enabled: true
    retries:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true
    distribution:
      percentiles-histogram:
        resilience4j.circuitbreaker.calls: true
        resilience4j.retry.calls: true
        resilience4j.bulkhead.calls: true
        resilience4j.timelimiter.calls: true

# Logging Configuration
logging:
  level:
    com.elearningsystem.examservice: DEBUG
    org.springframework.web: DEBUG

# JWT Configuration
jwt:
  secret: bXlTZWNyZXRLZXlGb3JKV1RUb2tlbkdlbmVyYXRpb25BbmRWYWxpZGF0aW9u
  expiration: 86400000 # 24 hours in milliseconds

# Resilience4j Configuration
resilience4j:
  # Circuit Breaker Configuration
  circuitbreaker:
    instances:
      subscription-service:
        register-health-indicator: true
        sliding-window-size: 10
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 2s
        
  # Retry Configuration
  retry:
    instances:
      subscription-service:
        max-attempts: 3
        wait-duration: 1s
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - java.net.ConnectException
          - java.net.SocketTimeoutException
          - feign.RetryableException
          - java.util.concurrent.TimeoutException
        ignore-exceptions:
          - java.lang.IllegalArgumentException
          
  # Timeout Configuration
  timelimiter:
    instances:
      subscription-service:
        timeout-duration: 3s
        cancel-running-future: true
        
  # Bulkhead Configuration
  bulkhead:
    instances:
      subscription-service:
        max-concurrent-calls: 10
        max-wait-duration: 1s 